services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pilotts_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP port
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pilotts_development
      RAILS_ENV: development
      SMTP_ADDRESS: mailcatcher
      SMTP_PORT: 1025
      SMTP_DOMAIN: localhost
      SMTP_AUTHENTICATION: plain
      SMTP_ENABLE_STARTTLS_AUTO: "false"
      MAILER_FROM_EMAIL: noreply@pilotts.com
      MAILER_DEFAULT_HOST: localhost:3000
    depends_on:
      db:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
